/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "simple_rpc.h"

bool_t
xdr_filestr (XDR *xdrs, filestr *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXSTRLEN))
		 return FALSE;
	return TRUE;
}
